name: "Release"
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: tar -czf client-web.tar.gz build
      - uses: softprops/action-gh-release@v1
        with:
          files: client-web.tar.gz
          generate_release_notes: true